#!/usr/bin/env bash
# A Bash script that transfers a file from client to a server.
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 OATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE"
"{USERNAME}@${IP}:~/"

if scp_exit_code=$?; then
    echo "File successfully transferred to ${USERNAME}@{IP}:~/"
else
    echo "File transfer failed."
    exit "$scp_exit_code"
fi

exit 0
