#!/usr/bin/env bash
# A Bash script that configures a new ubuntu machine running on the server

sudo apt-get update
sudo apt-get install -y nginx

# Allow HTTP traffic through the firewall for nginx and listening on port 80
sudo ufw allow 'Nginx HTTP'

# A page contains the string
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing our script
sudo nginx -t

# To restart nginx
sudo service nginx restart
