#!/usr/bin/env bash
# load balancer-01 login commands

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to IdentityFile
sssh-add ~/.ssh/school

# Username and IP Address
ssh ubuntu@52.91.151.59
