#!/usr/bin/env bash
# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Define Nginx configuration file
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
