#!/usr/bin/env bash
# Configuring a server
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart

#terminate the first nginx process ID
sudo pkill -o nginx
