#!/usr/bin/env bash
#Script that prints out strings using while and if

counter=0
while [ $counter -lt 10 ]
do
if [ $counter -eq 8 ]
then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
counter=$((counter+1))
done
