#!/usr/bin/env bash
#Prints clock using while

hour=0
minute=1
lines_displayed=0

while [ $hour -lt 13 ]
do
	while [$minute -lt 60 ]
	do
	echo "Hour: $hour"
	((hour+1))
done
((minute+1))
done | head -n 70
