#!/usr/bin/env bash
#Display the content of the current directory in a list format

for file in *; do
	if [[ ! "$file" == .* && "$file" == *-* ]]; then
		name_part=$(echo "file" | cut -d'-' -f2-)
		echo "$name_part"
	fi
done
