#!/usr/bin/env bash
# Run Nginx as less privelege
sudo sed -i '$/user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i '$/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
